name: noor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  iconsax: ^0.0.8
  get: ^4.6.5
  intl: ^0.19.0
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  flutter_localizations:
        sdk: flutter
  shared_preferences: ^2.2.3
  flutter_spinkit: ^5.2.1
  csc_picker: ^0.2.7
  http: ^1.2.0
  lottie: ^3.1.0
  workmanager: ^0.5.2
  alarm: ^3.1.4
  permission_handler: ^11.3.1
  audioplayers: ^6.0.0
  flutter_qiblah: ^3.0.3
  geolocator: ^11.1.0
  geocoding: ^3.0.0
  quran: ^1.3.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.2.0+3
  flutter_launcher_icons: ^0.13.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter_launcher_icons: 
  android: false
  ios: true
  image_path: "assets/logo/logo.png"

flutter:

  uses-material-design: true

  #------------- LOCAL ASSETS -------------#
  assets:
    - assets/images/background_images/
    - assets/images/svg/
    - assets/images/flags/
    - assets/lottie_animations/
    - assets/images/general/
    - assets/sounds/
    - assets/noor.db

  #------------- LOCAL FONTS -------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\poppins\Poppins-Thin.ttf
          weight: 100
        - asset: assets\fonts\poppins\Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets\fonts\poppins\Poppins-Light.ttf
          weight: 300
        - asset: assets\fonts\poppins\Poppins-Regular.ttf
          weight: 400
        - asset: assets\fonts\poppins\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\poppins\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\poppins\Poppins-Bold.ttf
          weight: 800
        - asset: assets\fonts\poppins\Poppins-ExtraBold.ttf
          weight: 900

    - family: Amiri
      fonts:
        - asset: assets\fonts\amiri\Amiri-Regular.ttf
          weight: 400
        - asset: assets\fonts\amiri\Amiri-Bold.ttf
          weight: 700

    - family: Quran
      fonts:
        - asset: assets\fonts\quran_font\Quran-Medium.ttf

    - family: Deco
      fonts:
        - asset: assets\fonts\quran_font\Deco-Type.ttf

flutter_intl:
  enabled: true
